
defaults:
  - _self_
  - target_function: branin
  - carps_task: branin
  - search_space: branin
  - override hydra/sweeper: HyperCARPS

hydra:
  sweeper:
    n_trials: ${carps_task.n_trials}
    sweeper_kwargs:
      optimizer_kwargs:
        _target_: carps.optimizers.hebo.HEBOOptimizer
        _partial_: true
        task: ${carps_task}
    search_space: ${search_space}
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}