
defaults:
  - _self_
  - target_function: branin
  - search_space: branin
  - override hydra/sweeper: HyperRS

hydra:
  sweeper:
    n_trials: 10
    sweeper_kwargs:
      max_parallelization: 0.8
      max_budget: 100
    search_space: ${search_space}
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}