
defaults:
  - _self_
  - target_function: branin
  - search_space: branin
  - override hydra/sweeper: HyperNevergrad

hydra:
  sweeper:
    n_trials: 10
    sweeper_kwargs:
      optimizer_kwargs:
        optimizer: 
          _target_: nevergrad.optimization.optimizerlib.CMA
          _partial_: true
          num_workers: 1
          budget: 100
    search_space: ${search_space}
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}