
defaults:
  - _self_
  - override hydra/sweeper: HyperSMAC

hydra:
  sweeper:
    n_trials: 10
    budget_variable: budget
    sweeper_kwargs:
      optimizer_kwargs:
        smac_facade: 
          _target_: smac.facade.blackbox_facade.BlackBoxFacade
          _partial_: true
          logging_level: 20  # 10 DEBUG, 20 INFO
        scenario:
          seed: 42
          n_trials: ${hydra.sweeper.n_trials}
          deterministic: true
          n_workers: 4
          output_directory: ${hydra.sweep.dir}
    search_space:
      hyperparameters:
        x0:
          type: uniform_float
          lower: -5
          upper: 10
          log: false
        x1:
          type: uniform_float
          lower: 0
          upper: 15
          log: false
          default_value: 2
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}

x0: 3
x1: 4

seed: None
budget: None 

spurious_var: 3.14